Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = "AKIAIBK4U445G5T7YJRA"
    aws.secret_access_key = "m/sHUQrpNhnr9vqUMaAaiRHqnz82pv43uBivkSFW"

	# Specify SSH keypair to use
	aws.keypair_name = "Boerse"


	# Specify region, AMI ID, and security group(s)
	aws.region = 'us-west-2'
	aws.ami = "ami-6f68cf0f"
	aws.instance_type = "t2.micro"
	aws.security_groups = "Boerse-WebServerSecurityGroup-53Q3QBI8VAA4"

	# Specify username and private key path
	override.ssh.username = "ec2-user"
    override.ssh.private_key_path = "Boerse.pem"
  end
  
  # Docker-compose specification
  config.vm.provision :docker
  config.vm.provision :docker_compose, yml: "/vagrant/docker-compose.yml", run: "always"

  # Docker run
  config.vm.provision "docker" do |d|
    d.run "mono_1", image: "mono"
  end
end